### ISSUE TITLE
Is the MSS210HKTRI working with this plugin?

### ISSUE THREAD

**Issue by andiweli** [Apollon77/ioBroker.meross#176]
Just asking...

**Comment by Apollon77** [comment]
This seems to be a new device. Then switch to debug log please and provide full log from adapter start.
ALso controll all relevant functions that are possible cia the meross app (turn on off, or whatever other functions are possible) and tell me the time when you did what and the order, so that I can match that to the logfile. also make some pauses maybe to have some separation between different functions.

Copy log from logfile on disk /opt/iobroker/log and not from admin. If you are curious about data send via email to iobroker@fischer-ka.de with reference to this issue.

**Comment by Apollon77** [comment]
MSS210 should be a normal WLAN Plug or?! In my eyes should work out of the box ... if not see above
