### ISSUE TITLE
Thermostat MTS200 Not working

### ISSUE THREAD

**Issue by Smarty0815** [Apollon77/ioBroker.meross#238]
The new thermostat MTS200 is not working. No data available in the objects.

**Comment by Apollon77** [comment]
Yes because the devices are unknown. some weeks ago we added MTS150 ... 

So turn debug log to on (Admin - Expert mode enable - Instances - extend meross instance and change loglevel from info to debug

Adapter will then restart.

Please get the log from logfile on disk (/opt/iobroker/logs/...) and send to me via email iobroker@fischer-ka.de and tell me the device ID of the MTS200 device.

Ideally (to have a rerally complete log) use the App and device to do EACH change possible (set every mode, change temps ....) - do this with pauses and write down the time and action .... Then I can map that to the logs ...but do maybe 30-60s break between each action!

**Comment by Smarty0815** [comment]
Kann ich noch etwas zur Lösung beisteuern?

**Comment by Apollon77** [comment]
No, it is on my list of topics and will come when I have time. Sorry

**Comment by Apollon77** [comment]
YOu have mail ... Check out GitHiub ... first experimental implementation

**Comment by Smarty0815** [comment]
Another addendum to the email. All devices are displayed as false under online, as in one of the last reported issue. After restarting the adapter, all devices are displayed as online again. However, devices were not offline. I start the debug mode.
