### ISSUE TITLE
Implementation of Meross Smart Door and Window Sensor Kit, MS200HHK

### ISSUE THREAD

**Issue by chibbez** [Apollon77/ioBroker.meross#354]
**Is your feature request related to a problem? Please describe.**
No, it seems to be about an not yet implemented sensor type

**Describe the solution you'd like**
Integeration of the new sensor to see the status (open / closed) from this door switch

**Describe alternatives you've considered**
nothing so far.

**Additional context**

IoBroker creates an object for the sensor below the smart hub with the states battery, online, switch.
In my example the deviceID is 160020127CA

Here is the output from the I-broker log when I open/close a window:

Received unknown data Appliance.Hub.Sensor.DoorWindow: {"doorWindow":[{"status":0,"sample":[[1,1703185859],[0,1703185864],[1,1703188893],[0,1703188898],[1,1703189115],[0,1703189120],[1,1703191479],[0,1703191538],[1,1703191637],[0,1703191648]],"lmTime":1703191648,"id":"1600201027CA","syncedTime":1703191648}]}

Received unknown data Appliance.Hub.Sensor.DoorWindow: {"doorWindow":[{"id":"1600201027CA","syncedTime":1703191637,"status":1,"sample":[[0,1703185611],[1,1703185859],[0,1703185864],[1,1703188893],[0,1703188898],[1,1703189115],[0,1703189120],[1,1703191479],[0,1703191538],[1,1703191637]],"lmTime":1703191637}]}

Thanks in advance.

**Comment by Apollon77** [comment]
In order to support new devices I would need a bit more information please. Ideally send as email to iobroker@fischer-ka.de with reference to this github issue.

1.) Switch on debug loglevel for the instance
2.) do any action with the device which is possible. not down the time and leave a pause between the actions that I can follow them in the logs. Check if you can do anything with the devcie (settings or such) in the meross app and also do this, not down infos and times

Send the full debug log as email.

**Comment by chibbez** [comment]
Thx, email with all info was sent.

**Comment by Apollon77** [comment]
found. give me some days ...

**Comment by Apollon77** [comment]
Grrmppff ... yes email is there but without any inofs what is what ... So which status is open and which is closed?

**Comment by Apollon77** [comment]
ahahh ... yes ... mixed emails ... ok have all infos, sorry

**Comment by Apollon77** [comment]
included in 1.17.0
